# Generated by Django 4.0 on 2022-02-22 15:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_notificaton_alter_package_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_booking',
            name='joinFrom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='package.joinfrom'),
        ),
        migrations.AddField(
            model_name='package_booking',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Booked'), (2, 'Completed'), (3, 'Canceled')], default=1),
        ),
        migrations.CreateModel(
            name='PackageCancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.package_booking')),
            ],
        ),
    ]
