# Generated by Django 3.2.7 on 2022-02-23 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_alter_notificaton_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='end_age',
        ),
        migrations.RemoveField(
            model_name='package',
            name='start_age',
        ),
    ]
