# Generated by Django 3.2.7 on 2022-02-23 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0006_auto_20220223_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='dayNo',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
