# Generated by Django 3.2.7 on 2022-02-23 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0007_alter_schedule_dayno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedate',
            name='maxPerson',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
