# Generated by Django 3.2.7 on 2022-02-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0008_alter_packagedate_maxperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_booking',
            name='state',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='package_booking',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
    ]
