# Generated by Django 4.0 on 2022-02-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0010_alter_package_max_altitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit_place',
            name='pin_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
